### ISSUE TITLE
its unable to fetch records from flipkart and always returns no product founds for every product on flipkart

### ISSUE THREAD

**Issue by Priyanshu7639** [mahitha-github/flask#1]

**Comment by mahitha-github** [comment]
Re: [mahitha-github/flask] Issue with Flipkart Product Fetch

Dear Priyanshu Singh,

Thank you for bringing this issue to my attention. The updated code for
addressing this problem is available in a different GitHub repository.
Please check the following link: Updated WebScrap Repository
<https://github.com/mahihubb/WebScrap>.

Feel free to reach out if you have any further questions or need additional
assistance.

Best regards,
Mahitha

**Comment by mahihubb** [comment]
Thank you for bringing this issue to my attention. The updated code for addressing this problem is available in a different GitHub repository. Please check the following link: Updated WebScrap Repository  https://github.com/mahihubb/WebScrap . Feel free to reach out if you have any further questions or need additional assistance. Best regards, Mahitha
